# Generated by Django 3.0.3 on 2020-03-18 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.FloatField(max_length=255)),
                ('kuantitas', models.FloatField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.FloatField(max_length=255)),
                ('deskripsi', models.TextField(max_length=255)),
                ('bahan', models.ManyToManyField(to='api.Bahan')),
                ('kategori', models.ManyToManyField(to='api.Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('jenisKelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=255)),
                ('nomorHp', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('jalan', models.CharField(max_length=500, null=True)),
                ('kecamatan', models.CharField(max_length=255, null=True)),
                ('kabkot', models.CharField(choices=[('Kabupaten', 'Kabupaten'), ('Kota', 'Kota')], max_length=255, null=True)),
                ('kota', models.CharField(max_length=255, null=True)),
                ('prov', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sedang diproses', 'Sedang diproses'), ('Sedang dikirim', 'Sedang dikirim'), ('Telah diterima', 'Telah diterima')], max_length=255, null=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('resep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Resep')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profil')),
            ],
        ),
    ]
